services:
  draco:
    image: prashantbhu/falcon:latest
    container_name: draco_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    environment:
      NODE_ENV: production
