name: Build and deploy Node.js app to Azure Web App - draco-falconai

on:
  push:
    branches:
      - main
    paths:
      - "apps/draco/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: npm install, build, and test
        run: |
          cd apps/draco
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Zip artifact for deployment
        run: |
          cd apps/draco
          zip -r ../../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AC103B15B8634424B9912C0D35DD6F34 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9629F3E7F9254849AF3A02716A7A207C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_62FDBEC015D34E2FBEAFF542C639EC78 }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "draco-falconai"
          slot-name: "Production"
          package: .
