name: Build and deploy Node.js app to Azure Web App - draco-falconai

on:
  push:
    branches:
      - main
    paths:
      - "apps/draco/**"
      - ".github/workflows/main_draco-falconai.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies at root
        run: pnpm install

      - name: Build and test app
        run: |
          cd apps/draco
          pnpm run build
          chmod +x start.sh
          echo "Build completed. Listing files:"
          ls -la

      - name: Create deployment package
        run: |
          cd apps/draco
          mkdir -p ../../release 
          pnpm deploy --target-directory=../../release
          echo "Deployment package created. Listing files:"
          ls -la ../../release

      - name: Zip artifact for deployment
        run: |
          cd ../../release
          zip -r ../release.zip .
          echo "Artifact zipped. Listing files:"
          ls -la ../release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: draco-app
          path: ../release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: draco-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip -d release
          cd release
          echo "Artifact unzipped. Listing files:"
          ls -la

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AC103B15B8634424B9912C0D35DD6F34 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9629F3E7F9254849AF3A02716A7A207C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_62FDBEC015D34E2FBEAFF542C639EC78 }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "draco-falconai"
          slot-name: "Production"
          package: .
